<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INUH101955" ignored="2" name="Default test" tests="5" failures="1" timestamp="2020-03-10T18:01:24 IST" time="7.324" errors="0">
  <testcase name="TC05_POST_CreateBookinDuplicateForSameDate" time="2.053" classname="com.hellofresh.test.NegativeTest">
    <failure type="com.hellofresh.utils.TestFailureException" message="Test step failed..">
      <![CDATA[com.hellofresh.utils.TestFailureException: Test step failed..
at com.hellofresh.utils.LoggerUtils.fail(LoggerUtils.java:124)
at com.hellofresh.utils.TestUtils.checkStatusCode(TestUtils.java:47)
at com.hellofresh.test.NegativeTest.TC05_POST_CreateBookinDuplicateForSameDate(NegativeTest.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC05_POST_CreateBookinDuplicateForSameDate -->
  <testcase name="TC08_POST_CreateBookingWithMissingData" time="1.066" classname="com.hellofresh.test.NegativeTest"/>
  <testcase name="TC08_POST_CreateBookingWithMissingData" time="0.959" classname="com.hellofresh.test.NegativeTest"/>
  <testcase name="TC08_POST_CreateBookingWithMissingData" time="0.948" classname="com.hellofresh.test.NegativeTest"/>
  <testcase name="TC08_POST_CreateBookingWithMissingData" time="0.956" classname="com.hellofresh.test.NegativeTest"/>
  <testcase name="TC06_GET_IncorrectUriTest" time="0.0" classname="com.hellofresh.test.NegativeTest">
    <ignored/>
  </testcase> <!-- TC06_GET_IncorrectUriTest -->
  <testcase name="TC07_POST_CheckinDateGreaterThanCheckoutDate" time="0.0" classname="com.hellofresh.test.NegativeTest">
    <ignored/>
  </testcase> <!-- TC07_POST_CheckinDateGreaterThanCheckoutDate -->
</testsuite> <!-- Default test -->
