<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INUH101955" name="com.hellofresh.test.NegativeTest" tests="6" failures="0" timestamp="2020-03-10T18:03:10 IST" time="5.319" errors="1">
  <testcase name="TC06_GET_IncorrectUriTest" time="0.897" classname="com.hellofresh.test.NegativeTest"/>
  <testcase name="TC07_POST_CheckinDateGreaterThanCheckoutDate" time="0.721" classname="com.hellofresh.test.NegativeTest"/>
  <testcase name="TC05_POST_CreateBookinDuplicateForSameDate" time="0.780" classname="com.hellofresh.test.NegativeTest">
    <error type="com.hellofresh.utils.TestFailureException" message="Test step failed..">
      <![CDATA[com.hellofresh.utils.TestFailureException: Test step failed..
at com.hellofresh.utils.LoggerUtils.fail(LoggerUtils.java:124)
at com.hellofresh.utils.TestUtils.checkStatusCode(TestUtils.java:47)
at com.hellofresh.test.NegativeTest.TC05_POST_CreateBookinDuplicateForSameDate(NegativeTest.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC05_POST_CreateBookinDuplicateForSameDate -->
  <testcase name="TC08_POST_CreateBookingWithMissingData" time="1.009" classname="com.hellofresh.test.NegativeTest"/>
  <testcase name="TC08_POST_CreateBookingWithMissingData" time="0.954" classname="com.hellofresh.test.NegativeTest"/>
  <testcase name="TC08_POST_CreateBookingWithMissingData" time="0.958" classname="com.hellofresh.test.NegativeTest"/>
</testsuite> <!-- com.hellofresh.test.NegativeTest -->
